export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("dish").del();
  await knex("dish").insert([
    {
      id: 1,
      name: "Ramen",
      description: "Noodles served in a flavorful broth",
      category: "Noodles",
      origin: "Fukuoka",
      localRanking: 1,
      internationalRanking: 2,
    },
    {
      id: 2,
      name: "Donburi",
      description: "Rice bowl with various toppings",
      category: "Rice",
      origin: "Various",
      localRanking: 2,
      internationalRanking: 6,
    },
    {
      id: 3,
      name: "Katsu Curry",
      description: "Breaded pork cutlet with Japanese curry and rice",
      category: "Meat",
      origin: "Tokyo",
      localRanking: 3,
      internationalRanking: 5,
    },
    {
      id: 4,
      name: "Udon",
      description: "Thick wheat noodles in a broth",
      category: "Noodles",
      origin: "Kagawa",
      localRanking: 4,
      internationalRanking: 8,
    },
    {
      id: 5,
      name: "Soba",
      description: "Thin buckwheat noodles",
      category: "Noodles",
      origin: "Nagano",
      localRanking: 5,
      internationalRanking: 10,
    },
    {
      id: 6,
      name: "Sushi",
      description: "Vinegared rice with raw fish or seafood",
      category: "Fish",
      origin: "Tokyo",
      localRanking: 6,
      internationalRanking: 1,
    },
    {
      id: 7,
      name: "Yakitori",
      description: "Grilled chicken skewers",
      category: "Meat",
      origin: "Tokyo",
      localRanking: 7,
      internationalRanking: 7,
    },
    {
      id: 8,
      name: "Tonkatsu",
      description: "Breaded and fried pork cutlet",
      category: "Meat",
      origin: "Nagoya",
      localRanking: 8,
      internationalRanking: 4,
    },
    {
      id: 9,
      name: "Miso Shiru",
      description: "Miso soup with tofu and seaweed",
      category: "Soup",
      origin: "Various",
      localRanking: 9,
      internationalRanking: 12,
    },
    {
      id: 10,
      name: "Onigiri",
      description: "Rice balls often with fillings",
      category: "Rice",
      origin: "Various",
      localRanking: 10,
      internationalRanking: 11,
    },
    {
      id: 11,
      name: "Gyoza",
      description: "Pan-fried dumplings filled with meat",
      category: "Meat",
      origin: "Utsunomiya",
      localRanking: 11,
      internationalRanking: 3,
    },
    {
      id: 12,
      name: "Tempura",
      description: "Deep-fried seafood or vegetables",
      category: "Fish",
      origin: "Tokyo",
      localRanking: 12,
      internationalRanking: 9,
    },
    {
      id: 13,
      name: "Okonomiyaki",
      description: "Savory Japanese pancake with various toppings",
      category: "Other",
      origin: "Osaka",
      localRanking: 13,
      internationalRanking: 13,
    },
    {
      id: 14,
      name: "Takoyaki",
      description: "Ball-shaped snacks filled with octopus",
      category: "Other",
      origin: "Osaka",
      localRanking: 14,
      internationalRanking: 14,
    },
    {
      id: 15,
      name: "Chirashi",
      description: "Bowl of vinegared rice topped with raw fish",
      category: "Fish",
      origin: "Hokkaido",
      localRanking: 15,
      internationalRanking: 15,
    },
    {
      id: 16,
      name: "Gyudon",
      description: "Rice bowl topped with sautéed beef and onions",
      category: "Rice",
      origin: "Tokyo",
      localRanking: 6,
      internationalRanking: 9,
    },
    {
      id: 17,
      name: "Oyakodon",
      description: "Rice bowl topped with chicken and egg",
      category: "Rice",
      origin: "Tokyo",
      localRanking: 7,
      internationalRanking: 13,
    },
    {
      id: 18,
      name: "Karaage",
      description: "Marinated and fried chicken pieces",
      category: "Meat",
      origin: "Oita",
      localRanking: 8,
      internationalRanking: 5,
    },
    {
      id: 19,
      name: "Nikujaga",
      description: "Beef and potato stew",
      category: "Meat",
      origin: "Tokyo",
      localRanking: 12,
      internationalRanking: 16,
    },
    {
      id: 20,
      name: "Shabu Shabu",
      description: "Japanese hotpot with thinly sliced meat",
      category: "Meat",
      origin: "Osaka",
      localRanking: 11,
      internationalRanking: 8,
    },
  ]);
}
